compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
machine_rank: 0
num_machines: 1
num_processes: 2
gpu_ids: all
mixed_precision: fp16
use_cpu: false
main_training_function: main

deepspeed_config:
  train_batch_size: 64
  gradient_accumulation_steps: 1
  fp16:
    enabled: true
  zero_optimization:
    stage: 2
    offload_param:
      device: cpu
  gradient_clipping: 1.0
  steps_per_print: 100
  zero_allow_untested_optimizer: true
  wall_clock_breakdown: false
